image: python:3.6.4

variables:
  PIP_CACHE_DIR: "MLOps Project 2023/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python --version
  - pip --version
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

stages:
  - build
  - lintest_flake8
  - lintest_pylint
  - unittest

build:
  stage: build
  script:
    - pip install -r requirements.txt
  only:
    - merge_requests
  artifacts:
    paths:
      - build/*

flake8:
  stage: lintest_flake8
  script:
    - echo "Starting lintest flake8 src/data..."
    - flake8 --max-line-length=120 --ignore=E128 src/data
    - echo "Starting lintest flake8 src/models..."
    - flake8 --max-line-length=120 --ignore=E128 src/models
  only:
    - merge_requests
  artifacts:
    paths:
      - lintest_flake8/*

pylint:
  stage: lintest_pylint
  script:
    - echo "Starting lintest pylint src/data..."
    - pylint src/data
    - echo "Starting lintest pylint src/models..."
    - pylint src/models
  only:
    - merge_requests
  artifacts:
    paths:
      - lintest_pylint/*

unittest:
  stage: unittest
  script:
    - python -m unittest src/unit_tests/signal_dataset.py
  only:
    - merge_requests
  artifacts:
    paths:
      - unittest/*
